schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "my_example_cube_extension"
version = "1.0.0"
name = "Circle Cube Generator"
tagline = "Creates cubes arranged in a circle"
maintainer = "Nile Walker <>"
# Supported types: "add-on", "theme"
type = "add-on"
# # Optional: link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
# tags = ["Animation", "Sequencer"]

blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
# # Optional: required by some licenses.
# copyright = [
#   "2002-2024 Developer Name",
#   "1998 Company Name",
# ]

# # Optional: list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# # Other supported platforms: "windows-arm64", "macos-x64"

# # Optional: bundle 3rd party Python modules.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
# wheels = [
#   "./wheels/hexdump-3.3-py3-none-any.whl",
#   "./wheels/jsmin-3.0.1-py3-none-any.whl",
# ]
wheels = [ "./wheels/defusedxml-0.7.1-py2.py3-none-any.whl", 
"./wheels/kiwisolver-1.4.7-cp312-cp312-win_amd64.whl", 
"./wheels/certifi-2024.12.14-py3-none-any.whl", 
"./wheels/PyYAML-6.0.2-cp312-cp312-win_amd64.whl", 
"./wheels/fonttools-4.55.3-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl", 
"./wheels/pandas-2.2.3-cp312-cp312-win_amd64.whl", 
"./wheels/pillow-11.0.0-cp312-cp312-manylinux_2_28_x86_64.whl",
"./wheels/six-1.17.0-py2.py3-none-any.whl", 
"./wheels/scipy-1.14.1-cp312-cp312-win_amd64.whl", 
"./wheels/urllib3-2.2.3-py3-none-any.whl", 
"./wheels/pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", 
"./wheels/opencv_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
"./wheels/pillow-11.0.0-cp312-cp312-win_amd64.whl", 
"./wheels/pytz-2024.2-py2.py3-none-any.whl", 
"./wheels/charset_normalizer-3.4.0-cp312-cp312-win_amd64.whl", 
"./wheels/numpy-2.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", 
"./wheels/idna-3.10-py3-none-any.whl", 
"./wheels/opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl",
"./wheels/tqdm-4.67.1-py3-none-any.whl", 
"./wheels/packaging-24.2-py3-none-any.whl", 
"./wheels/PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", 
"./wheels/contourpy-1.3.1-cp312-cp312-win_amd64.whl",
"./wheels/fonttools-4.55.3-cp312-cp312-win_amd64.whl",
"./wheels/numpy-2.2.0-cp312-cp312-win_amd64.whl", 
"./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl", 
"./wheels/charset_normalizer-3.4.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", 
"./wheels/tzdata-2024.2-py2.py3-none-any.whl", 
"./wheels/cycler-0.12.1-py3-none-any.whl", 
"./wheels/matplotlib-3.10.0-cp312-cp312-win_amd64.whl", 
"./wheels/requests-2.32.3-py3-none-any.whl", 
"./wheels/scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", 
"./wheels/supervision-0.25.1-py3-none-any.whl", 
"./wheels/kiwisolver-1.4.7-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", 
"./wheels/matplotlib-3.10.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
 "./wheels/fake_bpy_module-20241202-py3-none-any.whl",
 "./wheels/pyparsing-3.2.0-py3-none-any.whl", 
"./wheels/contourpy-1.3.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"]

# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.
#
# [permissions]
# network = "Need to sync motion-capture data to server"
# files = "Import/export FBX from/to disk"
# clipboard = "Copy and paste bone transforms"

# # Optional: advanced build settings.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# # These are the default build excluded patterns.
# # You only need to edit them if you want different options.
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  ".mypy_cache/",
  ".ruff_cache/"
]